### ISSUE TITLE
Feedback request: proposal to drop Rdiscount and Redcarpet support

### ISSUE THREAD

**Issue by benbalter** [github/pages-gem#179]
As we're preparing to upgrade to Jekyll 3.0.x, we're looking for ways to make things even easier for new users to get started. One point of unnecessary cognitive burden is choosing a markdown interpreter. 

*Kramdown? Rdiscount? Redcarpet? What's the difference? How do I choose? Why can't you just pick the best for me?* When I fire up WordPress or Microsoft Word or my phone, I don't choose the rendering engine. I trust the publisher to make that choice for me. Using Jekyll should be no different.

There used to be a lot of difference between the various Markdown rendering engines. Some supported some features, others implemented different features in different ways. Today, they've largely converged on a standard feature set, with Kramdown implementing most, if not all features (maybe not options), across all renderers.

### My question

**Other than speed, is there anything Rdiscount or Redcarpet does that Kramdown doesn't? Would you miss them terribly, or would your site fail to render if GitHub Pages dropped support for any markdown renderer other than Kramdown?**

*If there are any specific examples of features or syntaxes that RedCarpet or Rdiscount supports that Kramdown does not (rather than personal experience or preference), it'd go a long way to help inform our decision.*

### Rdiscount and Redcarpet breakdown:

* [Public sites explicitly using Redcarpet](https://github.com/search?l=yaml&q=%22markdown%3A+redcarpet%22+filename%3A_config.yml&ref=searchresults&type=Code&utf8=%E2%9C%93): ~24,000 (~2%)
* [Public sites explicitly using Rdiscount](https://github.com/search?utf8=%E2%9C%93&q=%22markdown%3A+rdiscount%22+filename%3A_config.yml&type=Code&ref=searchresults): ~18,000 (~2%)

### As a baseline:

* [Public sites still asking for Maruku, even though it no longer works](https://github.com/search?utf8=%E2%9C%93&q=%22markdown%3A+maruku%22+filename%3A_config.yml&type=Code&ref=searchresults): ~1,200. (~0%)
* [Public sites explicitly asking for Kramdown, even though its the default](https://github.com/search?utf8=%E2%9C%93&q=%22markdown%3A+kramdown%22+filename%3A_config.yml&type=Code&ref=searchresults): ~50,000 (~5%)
* [Public sites that specify *any* markdown generator](https://github.com/search?utf8=%E2%9C%93&q=%22markdown%22+filename%3A_config.yml&type=Code&ref=searchresults): ~90,000 (~9%)
* Sites just using the default with no markdown engine specified: 90%+

For open source projects I normally like to optimize for the 80% use case (not edge cases or power users), but here this means that 95%+ of users are using Kramdown (and 90%+ don't care enough to specify). For these numbers, you can assume 1M+ public sites.

*To note, this proposed change would only affect GitHub Pages. Users would be free to use any rendering engine they'd like when running Jekyll locally or on their own server.*

**Comment by Skyost** [comment]
Hi !
I am using the default markdown engine for my blog so I won't miss them.
What is the approximative upgrade date ?

Thanks.

**Comment by envygeeks** [comment]
The most obvious problem here is backticks.  Kramdown does not support the officially sanctioned Github way of doing things with backticks and this has come up a few times in our own tickets when users select Kramdown and the decision was made to not explicitly work around the lack of flexibility in processors so we never added support for them.

**Comment by geraldb** [comment]
FYI: You can use:

    kramdown:
       input: GFM

To add support for backticks. Might be a great default (In my humble opinion - I also prefer backticks for code block): Cheers.

**Comment by sevenseacat** [comment]
Also consider that there are _private_ repos also running blogs via GitHub pages, like my own. The percentages are probably fairly similar, but still.

**Comment by damncabbage** [comment]
I tried [switching over to Kramdown](https://github.com/damncabbage/damncabbage.github.io/blob/master/_config.yml#L18-L22) (with GFM as above), but:

1. Haven't gotten syntax-highlighting working at all on GitHub Pages itself. I've tried Coderay, Rouge and Pygments (what I used with Redcarpet), and have come up with nothing.
2. Locally, Pygments doesn't seem to work with Kramdown, and Coderay doesn't seem to know how to detect language based on whatever I give after the start of the code-fence; the highlighting looks rubbish with YAML, for example.

I've seen some mention of a blessed "Pretty Lights" highlighter that's not been released. I'm a bit in the dark here. What highlighter are we supposed to be using with Kramdown?

**Comment by geraldb** [comment]
Disclaimer: I'm just a Jekyll user.   
> What highlighter are we supposed to be using with Kramdown?
The official higlighter in Jekyll 3.0 is Rouge and it's also the official higlighter in the latest Kramdown, thus, I'd say Rouge, of course.

**Comment by Phlow** [comment]
I like Kramdown. I think to reduce the clutter is a good idea.

**Comment by jeremenichelli** [comment]
I prefer RedCarpet for Markdown syntax. In case it's deprecated is there a way I can configure Kramdown so I don't have to go and change all my posts's syntax? I don't want to wake up one day and see my site does not render as expected.

**Comment by MilanAryal** [comment]
:+1: Kramdown

**Comment by r-brown** [comment]
The numbers as of 2015-11-28 may be slightly different:

* [All public sites build using Jekyll](https://github.com/search?utf8=✓&q=filename%3A_config.yml&type=Code&ref=searchresults) 419,532 (100%)
* [Public sites explicitly using Redcarpet](https://github.com/search?l=yaml&q=%22markdown%3A+redcarpet%22+filename%3A_config.yml&ref=searchresults&type=Code&utf8=✓) 23,759 (~5.66%)
* [Public sites explicitly using Rdiscount](https://github.com/search?utf8=✓&q=%22markdown%3A+rdiscount%22+filename%3A_config.yml&type=Code&ref=searchresults) 18,337 (~4.37%)

We are also using _[kramdown](https://github.com/Labs64/netlicensing.io/blob/gh-pages/_config.yml#L22)_ on our sites, so this won't hurt us so much.
But other almost 50K (10%) users will get definitely a bad experience with this stack.

IMO this support shouldn't be simply switched off but the users should rather be notified in advance.

Best,

**Comment by benbalter** [comment]
> Haven't gotten syntax-highlighting working at all on GitHub Pages itself... Locally, Pygments doesn't seem to work with Kramdown

I can confirm syntax highlighting and Pygments both work Kramdown (and are actually handled at the Jekyll level, via the `highlight` tag).

> I prefer RedCarpet for Markdown syntax. 

@jeremenichelli can you provide some specific examples of where Kramdown doesn't support a syntax that RedCarpet does?

> All public sites build using Jekyll 419,532 (100%)

@r-brown to note, a site doesn't need a `_config.yml` file to be a Jekyll site (the number of Jekyll sites is roughly double that, by my records).

**Comment by benbalter** [comment]
One last call, if there are any specific examples of features or syntaxes that RedCarpet or Rdiscount supports that Kramdown does not (rather than personal experience or preference), it'd go a long way to help inform our decision.

**Comment by waldoj** [comment]
Nope, no problem for my Jekyll sites.

**Comment by benbalter** [comment]
> IMO this support shouldn't be simply switched off but the users should rather be notified in advance.

We still need to discuss things internally from a product/support perspective, but right now I'm hoping that when we move to Jekyll 3.0.x we will also announce a six-month sunset for Rdiscount and Redcarpet support (with warnings on push, similar to what we did with Maruku).

**Comment by jlord** [comment]
I would be sad!

> Kramdown does not support the officially sanctioned Github way of doing things 

:point_up: This.

I use Pages to host the site and documentation for `atom/electron`. This site uses the markdown documentation as it is in the GitHub repository. The problem is that GitHub.com renders markdown different than Pages. Redcarpet is the most similar, though it's still does not have feature parity. 

If Pages switches to Kramdown I'm guessing none of the code blocks in the Electron documentation will render correctly on the site? I think the ultimate (and kind of obvious) goal should be to have markdown on Pages and GitHub.com be the same.

**Comment by benbalter** [comment]
>  The problem is that GitHub.com renders markdown different than Pages. 

@jlord as @geraldb [suggested above](https://github.com/github/pages-gem/issues/179#issuecomment-160065802), have you tested putting Kramdown into GitHub-flavored Markdown mode?

```yml
kramdown:
   input: GFM
```

**Comment by ttimsmith** [comment]
:+1: I like Kramdown and don't find myself needing the others.

**Comment by holman** [comment]
> I can confirm syntax highlighting and Pygments both work Kramdown (and are actually handled at the Jekyll level, via the highlight tag).

From a "imma write some Markdown now" perspective, the `highlight` tag never made much sense to me, since you have to leave Markdown to use it. (Although the fenced code syntax we chose itself was a misstep too, in hindsight, but I digress). +1 for definitely using the `GFM` setting as a default in Jekyll; the interface should just be Markdown, and Markdown's flavor differences are confusing enough. GitHub should at least put a consistent foot forward.

**Comment by mattr-** [comment]
Let's flip the question around a little bit, if we can.

From a product/support perspective, what (if any) additional burden does supporting Redcarpet/Rdiscount cause Pages? I understand that it's not for free, but what harm are we causing by not removing it?

**Comment by envygeeks** [comment]
I would think there would be less burden on their build servers by allowing the C equivs.

**Comment by geraldb** [comment]
FYI: I've put together a simple test page for kramdown using the gfm mode (see [testgfm.html](http://viennahtml.github.io/testgfm.html) and the source [testgfm.md](https://github.com/viennahtml/viennahtml.github.io/blob/master/testgfm.md) using this settings -  it works as expected (if you turn off the hard_wrap) :-)

    markdown: kramdown
    
    kramdown:
      input: GFM
      hard_wrap: false

**Comment by jlord** [comment]
> have you tested putting Kramdown into GitHub-flavored Markdown mode?

@benbalter Hmm, I feel like if that had worked I wouldn't be in the situation I am now with the site and wouldn't have had so much back and forth with you over the past few months re: markdown/Pages. But it has been months now and memory is fuzzy so I will give it a go again. If there is true parity between GitHub.com and this then :sparkles:

**Comment by envygeeks** [comment]
@geraldb mind filing a ticket on Jekyll with those settings so I can add them to the Kramdown rewrite as default options?  I'll forget by the time I get about to working on it again but I think those would be sane defaults for Jekyll

**Comment by geraldb** [comment]
@envygeeks  Sorry I'm not at GitHub issue export (do not know how to reference the ticket) Find it at [jekyll-4202](https://github.com/jekyll/jekyll/issues/4202). Cheers. PS: Thanks for your great work. Keep it up.

**Comment by jeremenichelli** [comment]
I've tried this configuration locally:

```yml
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
```
And the result is that it works good except that inside the pre code tags I don't have the tokenization I had previously identifying comments for example so I can style them.

**Comment by envygeeks** [comment]
Yeah Kramdown doesn't support Pygments, it only supports Rouge and Coderay because both of those are pure Ruby and it's a pure Ruby Markdown processor.

**Comment by jeremenichelli** [comment]
If there's no native alternative for highlighting I'm against removing all Markdown engines except for Kramdown since you're removing a feature from Jekyll.

**Comment by envygeeks** [comment]
@jeremenichelli well... technically Pygments isn't a feature of Jekyll anymore, in 3.0 we switched to Rouge ourselves as the default processor, Pygments is an optional now.

**Comment by jeremenichelli** [comment]
@envygeeks well, but it's available, that's what I meant. My point is that I'm using Jekyll locally and I'm able to use highlighting, GitHub Pages at least would need to offer an alternative if *Kramdown* will be the only Markdown engine present.

**Comment by rdwatters** [comment]
**Disclaimer:** I'm pretty new to Jekyll (and web development in general), but right now the biggest inconsistencies for me while I write the content for my new blog on GH are codeblocks (eg, backticks, including a filename in addition to using GFM, Pygments Vs. Rouge).

**My 2&cent;:** Most of this has already been mentioned
* Settle on a *single markdown converter* (I've only used Redcarpet, but I'm willing to use Kramdown if that's the only option) and a *single highlighter*. 
* Set GFM as default for Kramdown (if this is the final choice). This is GH pages, after all. I'd love the ability to include a filename in addition to syntax after the triple backticks, but I know this is a nice-to-have and I don't think it's part of standard GFM any way.
* For syntax highlighting, whatever produces HTML that uses the same classes as pygments. I think this is fair since the library of CSS options for different languages seems far more extensive with pygments, and my attempts to use rouge required I add highlight.js, which I'm trying to avoid if possible. 
* **Concern:** Pretty Lights? I've heard talk of this as well. Will the syntax be identical to that of Rouge? Pygments? It'd be a bummer to have all new sites move to Rouge if they'll eventually need to be replaced by a native GH syntax highlighter.

**Comment by benbalter** [comment]
> If there's no native alternative for highlighting I'm against removing all Markdown engines except for Kramdown since you're removing a feature from Jekyll.

@envygeeks @jeremenichelli If I'm understanding correctly, Kramdown, in GFM mode, with Rouge should support the desired behavior (syntax highlighting via backticks).

**Comment by benbalter** [comment]
> Set GFM as default for Kramdown... +1 for definitely using the GFM setting as a default in Jekyll.. From a "imma write some Markdown now" perspective, the highlight tag never made much sense to me, since you have to leave Markdown to use it.

As always have to agree with @holman.

GFM for Kramdown would be a nice, sane default, but I'd [rather this be done in Jekyll-core](https://github.com/jekyll/jekyll/issues/4202), than specific to Pages, where a user using the default configuration locally would have a different experience than the default experience when generated via GitHub Pages (we currently don't have a way to set defaults that differ from Jekyll's defaults locally).

**Comment by gettalong** [comment]
If pygments should be a supported syntax highlighter in kramdown, it can easily be implemented since syntax highlighting is more or less plug-and-play. To start have a look at one of the current implementations https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/syntax_highlighter/rouge.rb

Regarding GFM: Since there is no spec for GFM, the implementation is currently just guess work.

**Comment by chloerei** [comment]
I prefer build on local, and push static files to GitHub Pages, that I will not be affected by the upgrade.

**Comment by envygeeks** [comment]
@benbalter Rouge uses different class names AFAIW which would mean everybody who currently uses Pygments would need to port their CSS, however... given it's Kramdown, you could probably just build a custom syntax highlighter for it, and I'd be happy to build it and ship a PR to do it if you like... out of all the things that could go wrong, Pygments vs. Rouge is probably the least relevant since it's the one that can be worked around the easiest.

**Comment by jeremenichelli** [comment]
Yeap, I think that the most critical thing here is not **silently** break other people styles because of this hiighlighting changes, if class names sets can be configured/maintain, then I'm ok with this.

**Comment by jeremenichelli** [comment]
@benbalter is there a way I can test this right now locally?

**Comment by envygeeks** [comment]
@jeremenichelli disable pygments in your `_config.yml`, do what @geraldb did and see how your site looks....

> The HTML output from Rouge is fully compatible with stylesheets designed for pygments.

Well.  I guess I have no more to worry about.  Everything I was concerned about has been addressed.

**Comment by geraldb** [comment]
FYI: There's an (old) article titled ["Syntax Highlighting in Jekyll With Rouge"](http://sacha.me/articles/jekyll-rouge/) for details on getting Jekyll with Rouge and Backticks (GFM) work / setup that might be of interest.  

Also if I may state the obvious @gettalong (see posting above) is the author of kramdown - the best source to ask ;-)  (As always - thanks for the great library. Keep it up.)

**Comment by jeremenichelli** [comment]
@envygeeks using last version of Jekyll with this config:
```yml
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
```
And I get no highlighting, just plain text inside the code tags. Maybe I have to install Rouge locally, but then that would be this is still not built inside Jekyll, right?

**Comment by geraldb** [comment]
@jeremenichelli   If you changed the _config have you tried to restart the server? For more tips, see [How to install Rogue in Jekyll](http://blog.ondrejsynacek.com/2015/10/09/how-to-install-rogue.html). Cheers.

**Comment by jeremenichelli** [comment]
@geraldb yes, I restarted the server. Though I did not install *Rouge* since I thought it was already supported in Jekyll. If that's not the case then my suggestion would be to propose Rouge to be present in Jekyll as Kramdown is, and then GitHub Pages can shut down other makrdown engines and leave *Kramdown only*, at least that's my humble opinion around this.

**Comment by gettalong** [comment]
@jeremenichelli  If you want to test kramdown with rouge, you can do the following (from a POSIX-Shell):

~~~ shell
$ echo -e "~~~ ruby\nclass New\nend\n~~~" | kramdown --syntax-highlighter rouge
~~~

Output with rouge:

~~~ html
<div class="highlighter-rouge"><pre class="highlight"><code><span class="k">class</span> <span class="nc">New</span>
<span class="k">end</span>
</code></pre>
</div>
~~~

If this works, then kramdown with rouge works. So if the output with Jekyll is not correct, then there is probably a problem with Jekyll.

Also note that if the rouge library is not installed, kramdown will fall back to not doing any highlighting. It doesn't currently emit a warning in such a case but this can be changed if needed.

Fallback output when rouge is not available:

~~~ html
<pre><code class="language-ruby">class New
end
</code></pre>
~~~

**Comment by gettalong** [comment]
@jeremenichelli Also note that you need kramdown >= 1.5.0 for rouge support.

**Comment by gettalong** [comment]
@jeremenichelli Yes, you need to have rouge installed locally if you build locally.

As for Github Pages, if the information on https://pages.github.com/versions/ is correct, kramdown is at version 1.5.0 but they don't have rouge installed. So it seems that Github Pages currently doesn't support rouge?

**Comment by jeremenichelli** [comment]
Well, this is already a bad sign, I imagine this can cause some fragmentation between Jekyll and GitHub Pages and that's not good in my opinion. I prefer features to be aligned across them.

**Comment by parkr** [comment]
> it seems that Github Pages currently doesn't support rouge?

That would potentially change. We would go the pure-Ruby route of kramdown + Rouge.

**Comment by jeremenichelli** [comment]
@parkr if that happens, then, no fragmentation across GitHubPages gem and highlighting engines. GitHub staff can potentially let everyone know in advance and that's a thumbs up to me.

**Comment by benbalter** [comment]
Sounds like we have a path forward. Thanks everyone for the feedback. The additional context is extremely helpful.

**Comment by envygeeks** [comment]
@benbalter @gettalong I'd slow down on that "path forward", today we tried to convert our largest site to Kramdown and ran into a problem, GFM doesn't actually enable fenced codeblocks the way they work on Github, <code>```sh</code> does *not* behave like <code>~~~sh</code> actually we get no highlighting at all with the former.

BTW this is on Jekyll 3.1.alpha through: https://github.com/jekyll/jekyll/blob/master/lib/jekyll/configuration.rb#L71-L72

I don't know if this is intended but it's certainly how it's behaving for us on `Kramdown 1.9`, for us it's not a big deal, we don't process with Github so we worked around it by pre-parsing our source before Jekyll get's to it, but it might affect others

**Comment by gettalong** [comment]
@envygeeks I get the following results when running on the command line (just kramdown):

Input:

    ```sh
    bash test
    ```

Output with `kramdown -i GFM`:

~~~ html
<div class="highlighter-coderay"><div class="CodeRay">
  <div class="code"><pre><span class="line-numbers"><a href="#n1" name="n1">1</a></span>bash test
</pre></div>
</div>
</div>
~~~

Output with `kramdown -i GFM --syntax-highlighter rouge`:

~~~ html
<div class="highlighter-rouge"><pre class="highlight"><code>bash <span class="nb">test</span>
</code></pre>
</div>
~~~

Seems about right to me.

**Comment by envygeeks** [comment]
@gettalong Given this snippet (taken from https://github.com/jekyll/docker):

<pre><code>
## Running

***If you do not provide a command then it will default to `jekyll s`.***

### Native Docker

```sh
# Switch to 80:80 or 4000:80 if you wish to use only Nginx with `jekyll build`
docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll \
  -it -p 127.0.0.1:4000:4000 jekyll/jekyll
```

### Docker-Machine

~~~sh
# Switch to 80:80 or 4000:80 if you wish to use only Nginx with `jekyll build`
docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll \
  -it -p $(docker-machine ip `docker-machine active`):4000:4000 \
    jekyll/jekyll
~~~
</code></pre>

Inside of "index.md" with a `_config.yml` that states `markdown: kramdown` with the default options (of which I linked to earlier) in 3.1.alpha on our builder server I get the following results:

```html
<p><code class="highlighter-rouge">sh
# Switch to 80:80 or 4000:80 if you wish to use only Nginx with `jekyll build`
docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll \
  -it -p 127.0.0.1:4000:4000 jekyll/jekyll
</code></p>
```

```html
<div class="highlighter-rouge"><pre class="highlight"><code><span class="c"># Switch to 80:80 or 4000:80 if you wish to use only Nginx with `jekyll build`</span>
docker run --rm --label<span class="o">=</span>jekyll --volume<span class="o">=</span><span class="k">$(</span><span class="nb">pwd</span><span class="k">)</span>:/srv/jekyll <span class="se">\</span>
  -it -p <span class="k">$(</span>docker-machine ip <span class="sb">`</span>docker-machine active<span class="sb">`</span><span class="k">)</span>:4000:4000 <span class="se">\</span>
    jekyll/jekyll
</code></pre>
</div>
```

Only the second one (the <code>~~~</code>) is properly highlighted.

**Comment by envygeeks** [comment]
The problem here is more than likely the <code>`</code> inside of the <code>```</code> yeah?  We should probably take this to the Kramdown ticket system instead of spamming here.

**Comment by gettalong** [comment]
On the command line I get the following output using `kramdown -i GFM --syntax-highlighter rouge --no-hard-wrap`:

~~~html
<h2 id="running">Running</h2>

<p><strong><em>If you do not provide a command then it will default to <code class="highlighter-rouge">jekyll s</code>.</em></strong></p>

<h3 id="native-docker">Native Docker</h3>

<div class="highlighter-rouge"><pre class="highlight"><code><span class="c"># Switch to 80:80 or 4000:80 if you wish to use only Nginx with `jekyll build`</span>
docker run --rm --label<span class="o">=</span>jekyll --volume<span class="o">=</span><span class="k">$(</span><span class="nb">pwd</span><span class="k">)</span>:/srv/jekyll <span class="se">\</span>
  -it -p 127.0.0.1:4000:4000 jekyll/jekyll
</code></pre>
</div>

<h3 id="docker-machine">Docker-Machine</h3>

<div class="highlighter-rouge"><pre class="highlight"><code><span class="c"># Switch to 80:80 or 4000:80 if you wish to use only Nginx with `jekyll build`</span>
docker run --rm --label<span class="o">=</span>jekyll --volume<span class="o">=</span><span class="k">$(</span><span class="nb">pwd</span><span class="k">)</span>:/srv/jekyll <span class="se">\</span>
  -it -p <span class="k">$(</span>docker-machine ip <span class="sb">`</span>docker-machine active<span class="sb">`</span><span class="k">)</span>:4000:4000 <span class="se">\</span>
    jekyll/jekyll
</code></pre>
</div>
~~~

So kramdown seems to do the correct thing in both cases. Maybe you can find out what is actually passed to kramdown as input?

**Comment by parkr** [comment]
@gettalong What is the Ruby code that the CLI produces? Jekyll uses the kramdown Ruby API, and it may be missing a configuration option or two that the kramdown CLI sets.

**Comment by envygeeks** [comment]
@gettalong @parkr I get the same broken result when running the command shown above with the source file, this is on Ubuntu 14.04 x64 Ruby 2.2.3p137, if you need more information:

```
ruby -r rbconfig -e 'puts RbConfig::CONFIG["configure_args"]'
 '--disable-install-doc' '--enable-shared' '--prefix=/usr/local'
```

```
ii  libffi-dev:amd64                                      3.1~rc1+r3.0.13-12ubuntu0.1
ii  libreadline6-dev:amd64                                6.3-4ubuntu2
ii  libssl-dev:amd64                                      1.0.1f-1ubuntu2.16
ii  libxml2-dev:amd64                                     2.9.1+dfsg1-3ubuntu4.5
ii  libxslt1-dev:amd64                                    1.1.28-2build1
ii  libyaml-dev:amd64                                     0.1.4-3ubuntu3.1
```

The result also happens on Alpine Linux 3.3 x64

**Comment by envygeeks** [comment]
@gettalong @parkr after I finish working on this Kramdown+Rouge segfault problem that keeps happening I'll jump into Pry and hit up our Kramdown processor and see exactly what content is passed, we did recently update it but... if it was a problem there I wouldn't get the same results when hitting Kramdown without Jekyll.

**Comment by gettalong** [comment]
@parkr See https://github.com/gettalong/kramdown/blob/master/bin/kramdown#L59, nothing really special.

@envygeeks I'm using kramdown 1.9.0 and ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux] on Ubuntu 15.04.

**Comment by gettalong** [comment]
@envygeeks Maybe you could try the following in an irb console:

~~~
require 'kramdown/document'
Kramdown::Document.new(File.read('/tmp/README.md'), input: :GFM, hard_wrap: false).to_html;
$".grep(/kramdown/).sort
~~~

The last line outputs all loaded kramdown source files. May this shows that some files are loaded from a wrong directory or something.

**Comment by envygeeks** [comment]
@parkr @gettalong I have feeling this is related to the bug in Rouge I'm currently working out, because it started working suddenly and then stopped working again, and stopped working again and then started again.  At this point I'm going to assume they are related.

**Comment by benbalter** [comment]
For those interested, I posted some additional context behind our decision [in this blog post](https://github.com/blog/2136-a-look-behind-our-decision-to-standardize-on-a-single-markdown-engine-for-github-pages).
